name: Feature Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  feature_test:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.4

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Run Testsuite
        run: vendor/bin/phpunit --testsuite Feature --testdox

  deploy:
    needs: phpunit
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Untasky Api
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.UNTASKY_SSH_HOST}}
          key: ${{secrets.UNTASKY_SSH_KEY}}
          username: ${{secrets.UNTASKY_SSH_USER}}

          script: |
            cd /var/www/html/untasky_api
            php artisan down
            git pull origin master
            composer install
            php artisan route:cache
            php artisan up
            echo 'Deployment successful'
